/* Generated By:JavaCC: Do not edit this line. StateMachineValuePaserConstants.java */
package com.wenyu7980.statemachine.guard.textguard;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface StateMachineValuePaserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 5;
  /** RegularExpression Id. */
  int DIGIT = 6;
  /** RegularExpression Id. */
  int STRING = 11;
  /** RegularExpression Id. */
  int IDENTIFIER = 12;
  /** RegularExpression Id. */
  int LETTER = 13;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_STRING = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<NUMBER>",
    "<DIGIT>",
    "\"\\\"\"",
    "<token of kind 8>",
    "<token of kind 9>",
    "<token of kind 10>",
    "\"\\\"\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "\"!\"",
    "\"-\"",
    "\"(\"",
    "\")\"",
    "\"*\"",
    "\"/\"",
    "\"+\"",
    "\"<>\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\">=\"",
    "\"<=\"",
    "\"&&\"",
    "\"||\"",
    "\"?\"",
    "\":\"",
    "\".\"",
    "\";\"",
  };

}
